GuestBook/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GuestBook.Models
{
    public partial class Message
    {
        public Message()
        {
            Replies = new HashSet<Reply>();
        }

        public int MessageId { get; set; }
        [Required(ErrorMessage ="*")]
        public string? MessageBody { get; set; }
        public DateTime MessageTime { get; set; }
        public int? UserId { get; set; }

        public virtual User? User { get; set; }
        public virtual ICollection<Reply> Replies { get; set; }
    }
}

GuestBook/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GuestBook.Models;
using GuestBook.Encryptions;

namespace GuestBook.Controllers
{
    public class MessagesController : Controller
    {
        private readonly GuestBookContext db;
        //private string user_id;
        public MessagesController(GuestBookContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            //Authorize...
            if(HttpContext.Session.GetString("userId") == null)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 });
            }
            string user_ID = HttpContext.Session.GetString("userId");
            int user_id = int.Parse(user_ID);
            var guestBookContext = db.Messages.Include(n=>n.User).Where(m => m.UserId == user_id);
            ViewBag.code = Encryptor.EncryptData(user_ID, "enc123");
            return View(guestBookContext.ToList());
        }
        public IActionResult Details(int? id)
        {
            if (HttpContext.Session.GetString("userId") == null) { return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 }); }
            if (id == null)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
            }

            var message = db.Messages.Include(m => m.User).FirstOrDefault(m => m.MessageId == id);
            if (message == null)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
            }

            return View(message);
        }
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("userId") == null) { return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 }); }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Message message,string code)
        {
            if (HttpContext.Session.GetString("userId") == null) { return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 }); }
            if(code == null)
            {
                ViewBag.requiredcode = "*";
                return View(message);
            }
            if (ModelState.IsValid)
            {
                message.UserId = int.Parse(Encryptor.DecryptData(code,"enc123"));
                message.MessageTime = DateTime.Now;
                db.Add(message);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(message);
        }
        public IActionResult Edit(int? id)
        {
            if (HttpContext.Session.GetString("userId") == null) { return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 }); }
            if (id == null)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
            }

            var message = db.Messages.Find(id);
            if (message == null)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
            }
            return View(message);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,Message message)
        {
            if (HttpContext.Session.GetString("userId") == null) { return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 }); }
            if (id != message.MessageId)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    message.MessageTime = DateTime.Now;
                    db.Update(message);
                    db.SaveChanges();
                }
                catch
                {
                   return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
                }
                return RedirectToAction("Index");
            }
            return View(message);
        }
        public IActionResult Delete(int? id)
        {
            if (HttpContext.Session.GetString("userId") == null) { return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 }); }
            if (id == null)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
            }
            var message = db.Messages.Include(m => m.User).FirstOrDefault(m => m.MessageId == id);
            if (message == null)
            {
                return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 404 });
            }
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index","Messages");
        }
    }
}

GuestBook/Controllers/RepliesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GuestBook.Models;

namespace GuestBook.Controllers
{
    public class RepliesController : Controller
    {
        private readonly GuestBookContext db;

        public RepliesController(GuestBookContext context)
        {
            db = context;
        }
        public IActionResult Create(int id)
        {
            if (HttpContext.Session.GetString("userId") == null) { return RedirectToAction("HttpStatusCodeHandler", "Error", new { statusCode = 401 }); }
            Reply reply = new Reply();
            reply.MessageId = id;
            return View(reply);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Reply reply)
        {
            if (ModelState.IsValid)
            {
                reply.ReplyTime =DateTime.Now;
                db.Add(reply);
                db.SaveChanges();
                return RedirectToAction("Index","Messages");
            }
            return View(reply);
        }
    }
}

GuestBook/Views/Messages/Create.cshtml
@model GuestBook.Models.Message

@{
    ViewData["Title"] = "Create";
}

<h1>Send a Message</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <h4>Your Friend's Code:</h4>
                <p class="text-danger">@ViewBag.requiredcode</p>
                <input name="code" class="form-control" />
            </div>
            <div class="form-group">
                <h4>Write a message</h4>
                <span asp-validation-for="MessageBody" class="text-danger"></span>
                <input asp-for="MessageBody" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Send" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>
<partial name="_ValidationScriptsPartial"></partial>

GuestBook/Views/Messages/Details.cshtml
@model GuestBook.Models.Message

@{
    ViewData["Title"] = "Details";
}

<h2>Message Details</h2>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Sender
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        <dt class = "col-sm-2">
            Time
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageTime)
        </dd>
        <dt class = "col-sm-2">
            Message
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageBody)
        </dd>
        <dt class = "col-sm-2">
            Replies
        </dt>
            @foreach (var item in Model.Replies)
            {
                <dd class = "col-sm-10"><div class="d-inline-block"> @item.ReplyBody </div> </dd>
            }
    </dl>
</div>
<div>
    <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model.MessageId">Edit</a> 
    <a class="btn btn-outline-info" asp-action="Index">Back to Messages</a>
</div>

GuestBook/Views/Messages/Edit.cshtml
@model GuestBook.Models.Message

@{
    ViewData["Title"] = "Edit Message";
}

<h2>Edit this message</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="MessageId" />
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <h4>Message</h4>
                <span asp-validation-for="MessageBody" class="text-danger"></span>
                <input asp-for="MessageBody" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                 <a class="btn btn-outline-danger" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

GuestBook/Views/Messages/Index.cshtml
@model IEnumerable<GuestBook.Models.Message>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
<h1 style="margin:auto;text-align:center;" class="text-primary">My Messages</h1>
<br />

<p class="alert-success p-3">
    To recieve new messages send this code to your friends: <strong>@ViewBag.code</strong>
</p>
<br />
    @foreach (var item in Model)
    {
        <div class="row">
         @*<h4>For You</h4>  *@
            <p class="mx-3">@item.MessageBody</p>
            <p>@item.MessageTime</p>
            <div class="d-flex justify-content-between">
                <div>
                    <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.MessageId">Edit</a>
                    <a class="btn btn-outline-success" asp-action="Details" asp-route-id="@item.MessageId">Details</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.MessageId" onclick="return confirm('Are you sure to delete this message??')" >Delete</a>
                </div>
                <div>
                    <a class="btn btn-outline-primary" asp-controller="Replies" asp-action="Create" asp-route-id="@item.MessageId">Reply</a>
                </div>
            </div>
        </div>
        <hr />
    }
</div>